apiVersion: v1
kind: Pod
metadata:
  name: ycsb-benchmark-0
  namespace: default
  labels:
    app: ycsb-benchmark
spec:
  containers:
  - name: ycsb-benchmark
    image: "nginx"
    resources:
      limits:
        cpu: 4
        memory: 20G
  restartPolicy: Never
  nodeSelector:

  tolerations:
    - key: role
      operator: Equal
      value: ycsb-benchmark
      effect: NoSchedule
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: ycsb-benchmark
---
apiVersion: v1
kind: Pod
metadata:
  name: ycsb-benchmark-1
  namespace: default
  labels:
    app: ycsb-benchmark
spec:
  containers:
  - name: ycsb-benchmark
    image: "nginx"
    resources:
      limits:
        cpu: 4
        memory: 20G
  restartPolicy: Never
  nodeSelector:

  tolerations:
    - key: role
      operator: Equal
      value: ycsb-benchmark
      effect: NoSchedule
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: ycsb-benchmark
---
apiVersion: v1
kind: Pod
metadata:
  name: ycsb-benchmark-2
  namespace: default
  labels:
    app: ycsb-benchmark
spec:
  containers:
  - name: ycsb-benchmark
    image: "nginx"
    resources:
      limits:
        cpu: 4
        memory: 20G
  restartPolicy: Never
  nodeSelector:

  tolerations:
    - key: role
      operator: Equal
      value: ycsb-benchmark
      effect: NoSchedule
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: ycsb-benchmark